### ISSUE TITLE
Create Speed selection broken

### ISSUE THREAD

**Issue by skippyall** [tweaked-programs/cccbridge#74] opened 2023-09-05 10:53 UTC
**Description**
The new speed selection of Create blocks like the Creative Motor are broken.

**To Reproduce**
1. Place a Creative Motor
2. Try selecting another speed by right clicking
3. Note that nothing happens

**Expected behavior**
The speed selection should work the same as without CC:C Bridge

**Software:**
 - Minecraft Version 1.20.1
 - Mod Version 1.6.2a
 - ModLoader Fabric

**Comment by skippyall** [comment] 2023-09-05 10:59
Confirmed that this happens just with CC:C Bridge, Create Fabric and CC Tweaked

**Comment by SammyForReal** [comment] 2023-09-05 11:08
Duplicate of #72 and #73
This has been fixed within the latest version _(v1.6.2**b**, you are using v1.6.2**a**)_

**Closed as completed by SammyForReal** 2023-09-05 11:08 UTC
Labels: bug, duplicate
