### ISSUE TITLE
Mod erroring on start-up 1.19.2

### ISSUE THREAD

**Issue by potential1energy** [tweaked-programs/cccbridge#49] opened 2023-06-30 02:19 UTC
**Description**
The game is erroring upon starting the game with the mods installed on game version 1.4.1

**To Reproduce**
1. Install Forge 43.2.4
2. Install Create 0.5.1.b - Forge
3. Install CC:C Bridge 1.19.2 1.4.1 - Forge
4. Install CC Tweaked 1.19.2 1.101.2 - Forge
5. Launch the game
6. See error

**Expected behavior**
The game launching into MC 1.19.4 without any errors

**Screenshots**
Error message when launched
![image](https://github.com/tweaked-programs/cccbridge/assets/75605951/9e6a2251-4c93-47e3-a573-5c240e007c9d)

**Software (please complete the following information):**
 - Minecraft Version 1.19.2
 - Mod Version 1.4.1
 - ModLoader Forge

**Comment by SammyForReal** [comment] 2023-06-30 05:43
Yep that is known. Duplicate of #28

**Closed as completed** 2023-06-30 05:43 UTC
Labels: bug
